
# Builder stage
FROM maven:3.5-jdk-8 as builder
WORKDIR /opt
COPY . /opt
RUN mvn clean install


# Final stage

FROM openjdk:17-jdk-slim-buster as final
# best practice is not to use root user
RUN useradd demo 
USER demo
COPY --from=builder  /opt/target/eureka-server-*.jar app.jar
ENTRYPOINT ["java","-jar","app.jar"]

