server:
  port: 9501

spring:
  application:
    name: jio-store-service
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: create
        
# disable eureka by default

eureka:
  client:
    enabled: false