
# config map to pass environment variables to containers
apiVersion: v1
data:
  spring.profiles.active: kubernetes,path
kind: ConfigMap
metadata:
  name: spring-config-map

---
# config map to pass environment variables to gateway-service
apiVersion: v1
data:
  jio.service.url: http://jio-microservice:9501
  jio.service.id: jio-service
  jio.service.path: Path= /jio/*
  airtel.service.url:  http://airtel-microservice:9502
  airtel.service.id: airtel-service
  airtel.service.path: Path= /airtel/*
  vodaphone.service.url: http://vodaphone-microservice:9503
  vodaphone.service.id: vodaphone-service
  vodaphone.service.path: Path= /vodaphone/*
kind: ConfigMap
metadata:
  name: api-gateway-config-map
---

# deployment config for spring cloud gateway service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  selector:
    matchLabels:
      app: gateway-service
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - name: gateway-service
        image: barathece91/gateway-service-k8s
        ports:
        - containerPort: 9500
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
              configMapKeyRef:
                  name: spring-config-map
                  key: spring.profiles.active
   
---
# deployment config for vodaphone-store-service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vodaphone-store-service
spec:
  selector:
    matchLabels:
      app: vodaphone-store-service
  replicas: 1
  template:
    metadata:
      labels:
        app: vodaphone-store-service
    spec:
      containers:   
      - name: vodaphone-store-service
        image: barathece91/vodaphone-store-service-k8s
        ports:
        - containerPort: 9000
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
              configMapKeyRef:
                  name: spring-config-map
                  key: spring.profiles.active   
---


# deployment config for jio-store-service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jio-store-service
spec:
  selector:
    matchLabels:
      app: jio-store-service
  replicas: 1
  template:
    metadata:
      labels:
        app: jio-store-service
    spec:
      containers:
      - name: jio-store-service
        image: barathece91/jio-store-service-k8s
        ports:
        - containerPort: 9500
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
              configMapKeyRef:
                  name: spring-config-map
                  key: spring.profiles.active
        - name: SPRING_CLOUD_GATEWAY_ROUTES[0]_URI
          valueFrom:
              configMapKeyRef:
                  name: api-gateway-config-map
                  key: jio.service.url
        - name: SPRING_CLOUD_GATEWAY_ROUTES[0]_ID
          valueFrom:
              configMapKeyRef:
                  name: api-gateway-config-map
                  key: jio.service.id
        - name: SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]
          valueFrom:
              configMapKeyRef:
                  name: api-gateway-config-map
                  key: jio.service.path
        - name: SPRING_CLOUD_GATEWAY_ROUTES[0]_FILTERS[0]
          value: StripPrefix=1 
        - name: SPRING_CLOUD_GATEWAY_ROUTES[1]_URI
          valueFrom:
              configMapKeyRef:
                  name: api-gateway-config-map
                  key: airtel.service.url
        - name: SPRING_CLOUD_GATEWAY_ROUTES[1]_ID
          valueFrom:
              configMapKeyRef:
                  name: api-gateway-config-map
                  key: airtel.service.id
        - name: SPRING_CLOUD_GATEWAY_ROUTES[1]_PREDICATES[0]
          valueFrom:
              configMapKeyRef:
                  name: api-gateway-config-map
                  key: airtel.service.path
        - name: SPRING_CLOUD_GATEWAY_ROUTES[2]_FILTERS[0]
          value: StripPrefix=1 
        - name: SPRING_CLOUD_GATEWAY_ROUTES[2]_URI
          valueFrom:
              configMapKeyRef:
                  name: api-gateway-config-map
                  key: vodaphone.service.url
        - name: SPRING_CLOUD_GATEWAY_ROUTES[2]_ID
          valueFrom:
              configMapKeyRef:
                  name: api-gateway-config-map
                  key: vodaphone.service.id
        - name: SPRING_CLOUD_GATEWAY_ROUTES[2]_PREDICATES[0]
          valueFrom:
              configMapKeyRef:
                  name: api-gateway-config-map
                  key: vodaphone.service.path
        - name: SPRING_CLOUD_GATEWAY_ROUTES[2]_FILTERS[0]
          value: StripPrefix=1             
---

# deployment config for airtel-store-service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: airtel-store-service
spec:
  selector:
    matchLabels:
      app: airtel-store-service
  replicas: 1
  template:
    metadata:
      labels:
        app: airtel-store-service
    spec:
      containers:
      - name: airtel-store-service
        image: barathece91/airtel-store-service-k8s
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: gateway-microservice
spec:
  selector:
    app: gateway-microservice
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9500
    targetPort: 9500
---
kind: Service
apiVersion: v1
metadata:
  name: jio-microservice
spec:
  selector:
    app: jio-microservice
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9501
    targetPort: 9501

---
kind: Service
apiVersion: v1
metadata:
  name: airtel-microservice
spec:
  selector:
    app: airtel-microservice
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9502
    targetPort: 9502
---

kind: Service
apiVersion: v1
metadata:
  name: vodaphone-microservice
spec:
  selector:
    app: vodaphone-microservice
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9503
    targetPort: 9503
    