
server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BarathArivazhagan/spring-cloud-gateway-routing.git/config-properties 
         

