{{- $deploymentName := .Values.airtel.name | default "airtel-service" -}}
{{- $containerPort := .Values.airtel.containerPort | default 9502 -}}
{{- $hostPort := .Values.airtel.hostPort | default 9502 -}}
{{- $replicas := .Values.airtel.replicas | default 1 -}}

{{- $deploymentImage := .Values.airtel.image -}} : {{- required "There is no defualt image value. A value must be given in the appropriate values file" -}}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deploymentName }}
spec:
  selector:
    matchLabels:
      app: {{ $deploymentName }}
  replicas: {{ $replicas }}
  template:
    metadata:
      labels:
        app: {{ $deploymentName }}
    spec:
      containers:
        - name: {{ $deploymentName }}
          image: {{ $deploymentImage }}
          ports:
            - containerPort: {{ $containerPort }}

---
kind: Service
apiVersion: v1
metadata:
  name: {{ $deploymentName }}
spec:
  selector:
    app: {{ $deploymentName }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ $$hostPort }}
      targetPort: {{ $containerPort }}